Automatic email
rage/mooc.fi pull request #225
Opened 2019-11-07 09:32 UTC by Ukonhattu

2019-11-21 13:19 UTC, nygrenh requested changes

2019-11-21 13:19 UTC, nygrenh commented on backend/resolvers/Query/EmailTemplate.ts
> +const EmaiLTemplates = (t: PrismaObjectDefinitionBlock<"Query">) => {
Weird casing

2019-11-21 13:19 UTC, nygrenh commented on backend/resolvers/Mutation/EmailTemplate.ts
> +      console.log(args)
Is this logging required?

2019-11-21 13:19 UTC, nygrenh commented on backend/bin/kafkaConsumer/userCourseProgressConsumer/generateUserCourseProgress.ts
> +      if (template) sendMail(user, template)
Can we split this to multiple lines?

2019-11-22 09:50 UTC, Ukonhattu commented on backend/resolvers/Query/EmailTemplate.ts
> +const EmaiLTemplates = (t: PrismaObjectDefinitionBlock<"Query">) => {
I call it PöhinÄCase

2019-11-22 09:53 UTC, nygrenh approved these changes

2019-11-22 10:04 UTC, merged