New module display
rage/mooc.fi pull request #276
Opened 2020-01-16 14:45 UTC by AVRH

New design for module display on the front page
Background colours of the modules changed to work with the new display style
ModuleSmallCourseCard colours edited to work with the new display style

2020-01-20 10:13 UTC, nygrenh commented on frontend/components/Home/ModuleDisplay/ModuleCourseCardList.tsx
> +        {showAll ? "Näytä rajatut" : "Näytä kaikki"}
These are not translated.

2020-01-20 10:15 UTC, nygrenh requested changes

2020-01-20 10:15 UTC, nygrenh commented on frontend/components/Home/ModuleDisplay/ModuleCoursesDisplay.tsx
> +        Opintokokonaisuuteen kuuluvat kurssit
Not translated

2020-01-20 10:18 UTC, nygrenh requested changes

2020-01-20 10:18 UTC, nygrenh commented on frontend/components/Home/ModuleDisplay/ModuleDisplay.tsx
> +  //@ts-ignore
Is this required?

2020-01-22 13:07 UTC, AVRH commented on frontend/components/Home/ModuleDisplay/ModuleDisplay.tsx
> +  //@ts-ignore
Leftover from development. good catch!

2020-01-22 13:07 UTC, AVRH commented on frontend/components/Home/ModuleDisplay/ModuleCoursesDisplay.tsx
> +        Opintokokonaisuuteen kuuluvat kurssit
Done

2020-01-22 13:07 UTC, AVRH commented on frontend/components/Home/ModuleDisplay/ModuleCourseCardList.tsx
> +        {showAll ? "Näytä rajatut" : "Näytä kaikki"}
Done

2020-01-22 17:45 UTC, nygrenh approved these changes

2020-01-22 17:45 UTC, merged