POC progress endpoint
rage/mooc.fi pull request #462
Opened 2020-08-07 12:06 UTC by mipyykko

- endpoint at `/api/courseprogress/{course}/{tmccourse}/{user}', where `course` is the quizzes course id, tmccourse its id and user the upstream user id.

Now outputs 
```
{
    "data": [
        {
            "id": "1e4af21e-7734-5282-a070-cc464a376e81",
            "pointAwarded": false
        },
...
       {
            "id": "48f05b72-10fd-5c83-b5a8-c104c7636376",
            "pointAwarded": false
        },
        {
            "id": 95055,
            "pointAwarded": true
        }
    ]
}
```

Can't get the tiers from the endpoint data, at least for now.

2020-08-11 12:47 UTC, Technopathic commented
This looks good to me, even without the tiers, as long as the IDs are there I can work with it.

2020-08-11 14:46 UTC, mipyykko commented
I'll have to refactor it to actually use the mooc.fi database, though.

2020-08-12 13:01 UTC, mipyykko commented
Endpoint now at `/api/baiprogress`, POST with access token to get current user building-ai progress. As the tiers are different courses for now, they are hardcoded. This also means that it doesn't know which exercises correspond to which, ie. if someone has answered beginner and intermediate tiers of same exercise, they're both listed separately.

Now using the mooc.fi db to query, outputs 

```
{
    "data": {
        "eac51365-75a9-4e79-ad59-ff8265b325b7": {
            "exercise_id": "eac51365-75a9-4e79-ad59-ff8265b325b7",
            "n_points": "666.000000000000000000000000000000",
            "part": 1,
            "section": 1,
            "max_points": 1,
            "completed": true,
            "tier": "beginner"
        },
        "06d803af-15dc-47c9-98bb-686da0ad5974": {
            "exercise_id": "06d803af-15dc-47c9-98bb-686da0ad5974",
            "n_points": "5.000000000000000000000000000000",
            "part": 1,
            "section": 1,
            "max_points": null,
            "completed": false,
            "tier": "intermediate"
        }
    }
}
```

The keys here are `exercise_id`, as repeated in the data. Not using the tmc exercise ids (95055 etc.) for intermediate/advanced, but quizzes exercise ids for all.

2020-08-13 08:23 UTC, nygrenh requested changes
Does this need to be a building ai specific endpoint? We could convert this to a general one and have the building ai frontend to query all three courses separately.

2020-08-13 13:19 UTC, mipyykko commented
Now it's `/api/progress/{id}` and only gets the exercises from provided course; doesn't return tier anymore since it doesn't know of it.

2020-08-18 07:41 UTC, nygrenh approved these changes

2020-08-18 07:41 UTC, merged