Migrate shibbo
rage/mooc.fi pull request #752
Opened 2021-06-10 11:39 UTC by mipyykko

Wonder if I left out anything.

2021-06-11 06:16 UTC, nygrenh requested changes

2021-06-11 06:16 UTC, nygrenh commented on helm/templates/ingress.yaml
> +          - path: /Shibboleth.sso
duplicate

2021-06-11 06:16 UTC, nygrenh commented on helm/templates/shibbo/shibbo-service.yml
> +    - port: 443
only one port needed

2021-06-11 06:16 UTC, nygrenh commented on shibbo/Dockerfile
> +# COPY shibboleth/attribute-map.xml /etc/shibboleth/attribute-map.xml
commment that mount these if building locally

2021-06-11 06:16 UTC, nygrenh commented on shibbo/Dockerfile
> +EXPOSE 80 443
expose just one thing, 80

2021-06-11 06:16 UTC, nygrenh commented on shibbo/bin/run.sh
> +httpd-shibd-foreground &
supervisord

2021-06-11 06:16 UTC, nygrenh commented on shibbo/src/server.ts
> +    res.redirect("https://www.mooc.fi/connection_success")
also support development mode

2021-06-11 11:21 UTC, mipyykko commented
`supervisord` now starts both the app and `shibd`. Running processes as different users seems a bit wonky in supervisor, now it's just root for all.

2021-06-15 06:25 UTC, nygrenh approved these changes
Looks fine, but in case something goes wrong, be ready to rollback the deployment (`helm history moocfi`, `helm rollback moocfi id`)

2021-06-15 06:39 UTC, merged